"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Search, Mail } from "lucide-react";

export default function HelpPage() {
  const [searchQuery, setSearchQuery] = useState("");

  const faqItems = [
    {
      question: "How do I generate content?",
      answer:
        "To generate content, navigate to the 'Generate' page from your dashboard. Choose the type of content you want to create, fill in the required fields such as topic and tone, and click the 'Generate' button. Our AI will then create content based on your inputs.",
    },
    {
      question: "What types of content can I create?",
      answer:
        "Our AI can generate various types of content including blog posts, social media posts, product descriptions, email copy, and short stories. We're constantly adding new content types to expand our offerings.",
    },
    {
      question: "How accurate is the AI-generated content?",
      answer:
        "While our AI strives for accuracy, it's important to review and fact-check the generated content. The AI uses patterns from its training data, which may not always reflect the most current information or specific expertise in all fields.",
    },
    {
      question: "Can I edit the generated content?",
      answer:
        "Yes, you can edit any content generated by our AI. After generation, you'll have the option to review and modify the content to better suit your needs or to add your personal touch.",
    },
    {
      question: "How do I save or export my generated content?",
      answer:
        "Once content is generated, you can save it to your account by clicking the 'Save' button. To export, look for the 'Export' or 'Download' option, which allows you to save the content in various formats such as .txt, .docx, or .pdf.",
    },
  ];

  const filteredFAQs = faqItems.filter(
    (item) =>
      item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Help Center</h1>

      <Card className="mb-8">
        <CardHeader>
          <CardTitle>How can we help you?</CardTitle>
          <CardDescription>
            Search our knowledge base or browse the topics below.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex space-x-2">
            <Input
              placeholder="Search for help..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="flex-grow"
            />
            <Button>
              <Search className="mr-2 h-4 w-4" />
              Search
            </Button>
          </div>
        </CardContent>
      </Card>

      <Tabs defaultValue="faq" className="space-y-4">
        <TabsList>
          <TabsTrigger value="faq">FAQ</TabsTrigger>
          <TabsTrigger value="guide">User Guide</TabsTrigger>
          <TabsTrigger value="contact">Contact Support</TabsTrigger>
        </TabsList>

        <TabsContent value="faq">
          <Card>
            <CardHeader>
              <CardTitle>Frequently Asked Questions</CardTitle>
              <CardDescription>
                Find quick answers to common questions.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {filteredFAQs.map((item, index) => (
                  <AccordionItem value={`item-${index}`} key={index}>
                    <AccordionTrigger>{item.question}</AccordionTrigger>
                    <AccordionContent>{item.answer}</AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="guide">
          <Card>
            <CardHeader>
              <CardTitle>User Guide</CardTitle>
              <CardDescription>
                Learn how to use our AI content generation platform effectively.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold mb-2">
                    Getting Started
                  </h3>
                  <p>
                    Welcome to our AI content generation platform! Here&apos;s a
                    quick guide to help you get started:
                  </p>
                  <ol className="list-decimal list-inside mt-2 space-y-1">
                    <li>Log in to your account</li>
                    <li>
                      Navigate to the &quot;Generate Content&quot; page from
                      your dashboard
                    </li>
                    <li>Choose the type of content you want to create</li>
                    <li>
                      Fill in the required fields (e.g., topic, tone, keywords)
                    </li>
                    <li>
                      Click &quot;Generate&quot; and wait for your AI-created
                      content
                    </li>
                    <li>Review and edit the generated content as needed</li>
                    <li>Save or export your content</li>
                  </ol>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2">
                    Tips for Best Results
                  </h3>
                  <ul className="list-disc list-inside space-y-1">
                    <li>Be as specific as possible with your inputs</li>
                    <li>Experiment with different tones and styles</li>
                    <li>Always review and fact-check the generated content</li>
                    <li>Use the editing tools to refine the output</li>
                    <li>Save your favorite settings for future use</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="contact">
          <Card>
            <CardHeader>
              <CardTitle>Contact Support</CardTitle>
              <CardDescription>
                Need more help? Our support team is here for you.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form className="space-y-4">
                <div className="space-y-2">
                  <label htmlFor="name" className="text-sm font-medium">
                    Name
                  </label>
                  <Input id="name" placeholder="Your name" />
                </div>
                <div className="space-y-2">
                  <label htmlFor="email" className="text-sm font-medium">
                    Email
                  </label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="Your email address"
                  />
                </div>
                <div className="space-y-2">
                  <label htmlFor="message" className="text-sm font-medium">
                    Message
                  </label>
                  <textarea
                    id="message"
                    placeholder="How can we help you?"
                    className="min-h-[100px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  />
                </div>
                <Button className="w-full">
                  <Mail className="mr-2 h-4 w-4" />
                  Send Message
                </Button>
              </form>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
